# -*- coding: utf-8 -*-
"""volume_of_a_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11seqtVhO8_Km0y1Vh-uHbMWl3jEd2EmR
"""

def calculate_volume_of_sphere(radius):
	pi = 3.14
	area = pi * radius * radius
	return area

radius1 = 30
area1 = calculate_volume_of_sphere(radius1)
print(f"The volume of a sphere with {radius1} is: {area1}")

radius2 = 40
area2 = calculate_volume_of_sphere(radius2)
print(f"The volume of a sphere with {radius2} is: {area2}")